### ISSUE TITLE
City & Countries

### ISSUE THREAD

**Issue by dani-fmena** [mamei-tech/tiketike#1]
Generar paises y ciudades correctamente.

**Comment by dani-fmena** [comment]
@ronielsh6 @acuevas920516  Metanle a eso a ver como queda. Cueando este cerramos el Issue. Fijense bien en todos los elementos donde se usa eso y el tema de las banderas como se cogen del filesystem.

**Comment by acuevas920516** [comment]
okok le metemos a eso, de todas formas adaptamos el seeder a nuestra convenienvia, luego te mandamos el enlace para que le heches un ojo
